### PR TITLE
Smart clone script: cnrv-clone.py

### PR DESCRIPTION
**Pull request by wsong83**
Usage:

~~~
$ ./cnrv-clone.py -h
usage: cnrv-clone.py [-h] [-b BRANCH] repository [directory]

Smart clone a repo from available CNRV images.

positional arguments:
  repository  URL of the remote repository to clone
  directory   Directory of the local clone.

optional arguments:
  -h, --help  show this help message and exit
  -b BRANCH   -b BRANCH   The branch to be cloned (default: master / auto-detect)
~~~

~~~
# example
$ ./cnrv-clone.py https://github.com/freechipsproject/rocket-chip
~~~

Users need to install the following packages:

+ argparse
+ subprocess
+ stdconfigparser

Potential issues:

+ The way that I use subprocess is kind of dangerous for certain security-critical users. I wonder if there is any better way to run git commands?
+ By a quick look, I cannot figure out how to use gitpython efficiently. May be you can help on it?
+ I need to add functions to fix the HEAD branch issue, which is caused by the lack of default branch during the clone process.
+ Duplicated references are stored. (Just download a repo and run `git branch -av`)

### CODE REVIEW

**Comment by wsong83** [comment]
Merge it to make some progress.

**Comment by xfguo** [comment]
@wsong83 sorry, it's too busy for these days.

**Comment by xfguo** [comment]
can we build a pure bash script instead of python?

**Comment by wsong83** [comment]
It would be difficult to parse the .gitmodules file in batch unless there is an easy way to figure out the remote URLs for all submodules using git commands or sed somehow.
Sed with regular expression might be possible.
That would be another degree of complexity I cannot afford right now.

Or, is there a way to compile python to some generic bytecode?

I do share your concern that requiring installing python package before running the script might be proved too much a hassle.

**Pull request merged**
